- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-04912852a99136d2b
    ami_id: sg-04912852a99136d2b
    env: dev
    instances:
    - mongodb
    - catalogue
  tasks: 
- name: create a ec2 instance 
  amazon.aws.ec2_instance:
    instance_type: "t3.micro"
    security_group: "{{sg_id}}"
    image_id: "{{ami_id}}"
    name: "{{item}}-{{env}}"
    tags:
      Project: roboshop
      Component: "{{item}}"
      Environment: "{{env}}"
      Name: "{{item}}-{{env}}"
    loop: "{{instances}}"
    register: ec2_output

- name : print the output
  ansible.buitin.debug:
      msg: "{{ec2_output}}"