- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-04912852a99136d2b
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instances:
      - mongodb
      - catalogue

  tasks:
    - name: create a ec2 instance
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"

    - name: create r53 records
      amazon.aws.route53:
       state: present
       Zone: "{ domain_name }}"
       record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
       type: A
       ttl: 1
       value: "{{ item.instances[0].public_ip_address }}"
       wait: true
      value: "{{ item.instances[0].public_ip_address }}"
       
